[tools]
node      = "20.0.0"
rust      = "1.78.0"
golang    = "1.22.0"
php       = "8.3.0"
ruby      = "3.3.0"
java      = [ "21.0.0", "17.0.0" ]
opam      = "2.1.0"
usage     = "0.1.9"
neovim    = [ "0.9.5", "0.10.0" ]

[settings]
experimental = true
