[tools]
bun       = "1.0.0"
deno      = "1.39.0"
node      = [ "21.0.0", "20.0.0", "18.0.0" ]
flutter   = "3.16.0"
rust      = "1.75.0"
golang    = "1.21.1"
php       = "8.3.0"
ruby      = "3.3.0"
java      = ["21.0.0", "17.0.0", "11.0.0"]
opam      = "2.1.0"
python    = [ "3.12.0", "3.9.0" ]

[settings]
experimental = true
