import = [
  "~/.config/alacritty/colors/color.toml"
]

live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/usr/bin/fish"
args = ["--login", "--interactive"]

[window]
decorations = "none"

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true

[font]
size = 12

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.bold_italic]
family = "Berkeley Mono"
style = "BoldItalic"
