import = [
  "~/.config/alacritty/colors/color.toml"
]

live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/usr/bin/fish"
args = ["--login", "--interactive"]

[window]
padding.x = 5
padding.y = 5
decorations = "none"

[font]
size = 14

# [font.normal]
# family = "Monaspace Neon"
# style = "Regular"

# [font.normal]
# family = "Monaspace Argon"
# style = "Regular"

[font.normal]
family = "Monaspace Radon"
style = "Regular"

# [font.normal]
# family = "Monaspace Krypton"
# style = "Regular"
 
# [font.normal]
# family = "Monaspace Xenon"
# style = "Regular"
