format = """
[┌](bold green) [$all](bold white) $fill $nodejs $cmd_duration $jobs $time $line_break\
[│](bold green) $line_break\
[└](bold green) $character\
"""

[character]
success_symbol = "[λ](bold green)"
vimcmd_symbol = "[λ](bold purple)"
vimcmd_visual_symbol = "[λ](bold yellow)"
error_symbol = "[λ](bold red)"

[line_break]
disabled = false

[fill]
symbol = " "

[directory]
style = "bold white"
read_only = " "
truncation_length = 4
truncation_symbol = ""
truncate_to_repo = true

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[cmd_duration]
style = "yellow"
format = "[$duration]($style)"

[memory_usage]
symbol = " "

[git_metrics]
disabled = false

[git_branch]
symbol = " "
style = "bright-black"
format = "[on $symbol$branch]($style) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
format = "[$symbol($version )]($style)"

[rust]
symbol = " "

[c]
symbol = " "

[python]
symbol = " "

[lua]
symbol = "󰢱 "

[java]
symbol = " "
