git_protocol: https
editor: nvim
prompt: enabled
pager:
aliases:
    co: pr checkout
    clone: repo clone
    find: repo list
    view: repo view --web
    edit: repo edit
http_unix_socket:
browser:
