[colors]

ansi = [
  "#1c252c",
  "#e05f65",
  "#78dba9",
  "#f1cf8a",
  "#70a5eb",
  "#c68aee",
  "#74bee9",
  "#dee1e6" 
]

brights = [
  "#384148",
  "#fc7b81",
  "#94f7c5",
  "#ffeba6",
  "#8cc1ff",
  "#e2a6ff",
  "#90daff",
  "#fafdff"
]

background = "#171a1f"

brights = [
  "#555555",
  "#ff5555",
  "#55ff55",
  "#ffff55",
  "#5555ff",
  "#ff55ff",
  "#55ffff",
  "#ffffff",
]

cursor_bg = "#dee1e6"
cursor_border = "#fafdff"
cursor_fg = "#22262e"
foreground = "#b6beca"
selection_bg = "#575268"
selection_fg = "#D9E0EE"

[colors.indexed]

[metadata]
name = "Decay (Default)"
origin_url = "https://github.com/decaycs/decay-terms/blob/main/wezterm/wezterm.lua"
