[tools]
flutter = "latest"
java = "latest"
opam = "latest"
rust = "latest"
go = "latest"
bun = "latest"
node = "latest"
php = "latest"
ruby = "latest"
neovim = "nightly"

[settings]
experimental = true
