format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

# [line_break]
# disabled = true

[directory]
read_only = " "
truncation_length = 4
truncation_symbol = ""
truncate_to_repo = true

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[battery]
disabled = true

# [rust]
# symbol = " "
#
# [c]
# symbol = " "
#
# [python]
# symbol = " "
#
# [lua]
# symbol = "󰢱 "
#
# [java]
# symbol = " "
