theme = "onedarker"

[editor]
color-modes = true
true-color = true
line-number = "relative"
bufferline = "never"
scrolloff = 0
mouse = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_above"]
C-w = [":write-all"]
C-q = [":quit"]

[editor.statusline]
left = ["mode", "spinner", "file-name"]

[editor.lsp]
display-messages = true
