[tools]
node      = "20.14.0"
bun       = "1.1.10"
rust      = "1.78.0"
golang    = "1.22.0"
php       = "8.3.7"
ruby      = "3.3.0"
elixir    = "1.16.3"
erlang    = "26.0.2"
opam      = "2.1.6"
gleam     = "1.2.1"
usage     = "0.3.0"

[settings]
experimental = true
